#
# dicom-xnat-sop: modality-sessions.properties
# XNAT http://www.xnat.org
# Copyright (c) 2017, Washington University School of Medicine
# All Rights Reserved
#
# Released under the Simplified BSD.
#

MR = mrSessionData
PT = petSessionData
CT = ctSessionData
XA = xaSessionData
US = usSessionData
IVUS = usSessionData
RT = rtSessionData
CR = crSessionData
OPT = optSessionData
MG = mgSessionData
DX = dxSessionData
NM = nmSessionData
SR = srSessionData
SC = otherDicomSessionData
OT = otherDicomSessionData
SM = smSessionData
GM = gmSessionData
RF = rfSessionData
ES = esSessionData
XC = xcSessionData
RG = rgSessionData
DMS = dmsSessionData
CFM = cfmSessionData
PA = paSessionData
ECG = ecgSessionData
EMG = emgSessionData
EOG = eogSessionData
RESP = respSessionData
POS = posSessionData
OBJ = objSessionData
EEG = eegSessionData
ANN = otherDicomSessionData