/*
 * xdat-data-builder: build.gradle
 * XNAT https://www.xnat.org
 * Copyright (c) 2021, Washington University School of Medicine
 * All Rights Reserved
 *
 * Released under the Simplified BSD.
 */

/*
 * Builds the xdat-data-builder Gradle plugin, which contains all functionality required
 * to generate code, display documents, view templates, and more from XNAT data types as
 * defined in the XNAT standard XSD format.
 */

buildscript {
    ext {
        vXnat = "1.10.0-RC2-SNAPSHOT"
    }
}

plugins {
    id "groovy"
    id "maven-publish"
    id "jacoco"
    id "java-gradle-plugin"
    id "idea"
    id "eclipse"
    id "com.gradle.plugin-publish" version "1.3.0"
    id "io.spring.dependency-management" version "1.0.11.RELEASE"
    id "net.linguica.maven-settings" version "0.5"
}

group "org.nrg.xdat.build"
version vXnat
description "XDAT Data Builder Gradle Plugin"

repositories {
    mavenLocal()
    maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-release" }
    maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-snapshot" }
    mavenCentral()
}

sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21

configurations {
    all*.exclude group: "avalon-framework"
    all*.exclude group: "avalon-logkit"
    all*.exclude group: "com.metaparadigm"
    all*.exclude group: "com.sun.mail"
    all*.exclude group: "excalibur-component"
    all*.exclude group: "excalibur-instrument"
    all*.exclude group: "excalibur-logger"
    all*.exclude group: "excalibur-pool"
    all*.exclude group: "fop"
    all*.exclude group: "geronimo-spec"
    all*.exclude group: "hsqldb"
    all*.exclude group: "imagej"
    all*.exclude group: "jamon"
    all*.exclude group: "jakarta-regexp"
    all*.exclude group: "org.apache.geronimo.specs"
    all*.exclude group: "velocity"
    all*.exclude group: "xmlrpc"
    all*.exclude group: "ant", module: "ant"
    all*.exclude group: "commons-email", module: "commons-email"
    all*.exclude group: "edu.ucar", module: "netcdf"
    all*.exclude group: "javax.jms", module: "jms"
    all*.exclude group: "javax.mail", module: "mail"
    all*.exclude group: "javax.servlet", module: "servlet-api"
    all*.exclude group: "javax.sql", module: "jdbc-stdext"
    all*.exclude group: "javax.transaction", module: "jta"
    all*.exclude group: "jdbc", module: "jdbc"
    all*.exclude group: "jms", module: "jms"
    all*.exclude group: "jython", module: "jython"
    all*.exclude group: "org.codehaus.groovy", module: "groovy-all"
    all*.exclude group: "org.nrg", module: "nrg"
    all*.exclude group: "net.sf.saxon", module: "saxon"
    all*.exclude group: "stax", module: "stax-api"
    all*.exclude group: "xerces"
    all*.exclude group: "xml-apis", module: "xml-apis"
    all*.exclude module: "commons-beanutils-core"
    all*.exclude module: "log4j-slf4j-impl"
    all*.exclude module: "pipelineCNDAXNAT"
    all*.exclude module: "slf4j-simple"
    all*.exclude group: "fulcrum"
}

dependencyManagement {
    imports {
        mavenBom "org.nrg:parent:${vXnat}"
    }
    generatedPomCustomization {
        enabled = false
    }
}

def vXdatCore = dependencyManagement.importedProperties["xdat.version"]
def vConfig = dependencyManagement.importedProperties["nrg.config.version"]
def vFramework = dependencyManagement.importedProperties["nrg.framework.version"]
def vNotify = dependencyManagement.importedProperties["nrg.notify.version"]
def vPrefs = dependencyManagement.importedProperties["nrg.prefs.version"]
def vSpring = dependencyManagement.importedProperties["spring-framework.version"]
def vSpringSecurity = dependencyManagement.importedProperties["spring-security.version"]
def vJackson = dependencyManagement.importedProperties["jackson.version"]
def vCommonsLang3 = dependencyManagement.importedProperties["commons-lang3.version"]
def vCommonsCollections = dependencyManagement.importedProperties["commons-collections.version"]
def vCommonsIo = dependencyManagement.importedProperties["commons-io.version"]
def vGuava = dependencyManagement.importedProperties["guava.version"]
def vJunit = dependencyManagement.importedProperties["junit.version"]



// Note: we have to include dependency versions here because the Gradle plugin mechanism doesn't work
// with dependency management, resulting in error messages about not being able to find the version.
dependencies {
    implementation platform("org.nrg:parent:${vXnat}")

    implementation("org.nrg.xdat:core:${vXdatCore}") {
        transitive = false
    }
    implementation("org.nrg:config:${vConfig}") {
        transitive = false
    }
    implementation("org.nrg:framework:${vFramework}") {
        transitive = false
    }
    implementation("org.nrg:notify:${vNotify}") {
        transitive = false
    }
    implementation("org.nrg:prefs:${vPrefs}") {
        transitive = false
    }

    implementation "org.springframework:spring-web:${vSpring}"
    implementation "org.springframework.security:spring-security-core:${vSpringSecurity}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${vJackson}"
    implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:${vJackson}"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-hibernate5:${vJackson}"
    implementation "org.apache.commons:commons-lang3:${vCommonsLang3}"
    implementation "commons-collections:commons-collections:${vCommonsCollections}"
    implementation "commons-io:commons-io:${vCommonsIo}"
    implementation "com.google.guava:guava:${vGuava}"

    testImplementation gradleTestKit()
    testImplementation "junit:junit:${vJunit}"
}

jacoco {
    toolVersion = dependencyManagement.importedProperties["jacoco.version"]
}

jacocoTestReport {
    reports {
        xml.required = false
        csv.required = false
        html.required = true
    }
}

def extManifest = manifest {
    attributes "Application-Name": project.description,
            "Build-Date": new Date(),
            "Build-Number": System.getenv().BUILD_NUMBER?.toInteger() ?: "Manual",
            "Implementation-Version": project.version
}

java {
    withJavadocJar()
    withSourcesJar()
}


jar {
    dependsOn test
    enabled = true
    manifest {
        from extManifest
    }
}

gradlePlugin {
    plugins {
        xdatDataBuilderPlugin {
            id = "org.nrg.xdat.build.xdat-data-builder"
            implementationClass = "org.nrg.xdat.build.XdatDataBuilderPlugin"
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            pom.withXml {
                def root = asNode()
                root.appendNode("name", "XDAT Data Builder Gradle plugin")
                root.appendNode("description", "Gradle plugin supporting code generation and integration of the core XNAT web application and XNAT modules.")
                root.appendNode("url", "https://bitbucket.org/xnatdev/xdat-data-builder")
                root.appendNode("inceptionYear", "2016")

                def scm = root.appendNode("scm")
                scm.appendNode("url", "https://bitbucket.org/xnatdev/xdat-data-builder")
                scm.appendNode("connection", "scm:https://bitbucket.org/xnatdev/xdat-data-builder.git")
                scm.appendNode("developerConnection", "scm:git://bitbucket.org/xnatdev/xdat-data-builder.git")

                def license = root.appendNode("licenses").appendNode("license")
                license.appendNode("name", "Simplified BSD 2-Clause License")
                license.appendNode("url", "https://xnat.org/about/license.php")
                license.appendNode("distribution", "repo")

                def developers = root.appendNode("developers")
                def rherrick = developers.appendNode("developer")
                rherrick.appendNode("id", "rherrick")
                rherrick.appendNode("name", "Rick Herrick")
                rherrick.appendNode("email", "jrherrick@wustl.edu")

                def tolsen = developers.appendNode("developer")
                tolsen.appendNode("id", "timolsen23")
                tolsen.appendNode("name", "Tim Olsen")
                tolsen.appendNode("email", "tim@xnetworks.io")
            }
        }
    }

    repositories {
        maven {
            // url "https://nrgxnat.jfrog.io/nrgxnat/gradle-plugins-${project.version.endsWith("-SNAPSHOT") ? "snapshot" : "release"}"
            url "https://nrgxnat.jfrog.io/nrgxnat/libs-${project.version.endsWith("-SNAPSHOT") ? "snapshot" : "release"}"
            // The value for name must match <id> in ~/.m2/settings.xml
            name = "XNAT_Artifactory"
        }
    }
}

