/*
 * xdat-data-builder: settings.gradle
 * XNAT https://www.xnat.org
 * Copyright (c) 2020, Washington University School of Medicine
 * All Rights Reserved
 *
 * Released under the Simplified BSD.
 */

pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-release" }
        maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-snapshot" }
        mavenCentral()
    }
}

rootProject.name = "xdat-data-builder"
